# Extra of NumPy

To understand what is the NumPy in python

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
print(np.__version__)

2.2.6


In [7]:
# create a numpy ndarray object

print(type(arr))

<class 'numpy.ndarray'>


In [11]:
# use a tuple to create a numpy array 

arr1 = np.array((1,2,3,4,5,6))
print(arr1)

[1 2 3 4 5 6]


In [12]:
print(type(arr1))

<class 'numpy.ndarray'>


> dimensions in arrays: a dimension in ararys is one level of array depth (nested arrays)

### O-D Arrays

0-D arrays, or Scalars, are the elements in an array. each value in an array is a 0-D array

In [14]:
# create a 0-D array with value 42

import numpy as np
arr = np.array(42)
print(arr)

42


### 1-D Arrays

an array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

In [15]:
# create a 1-D array containing the values 1,2,3,4,5:

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### 2-D Arrays
an array that has 1-D arrays as its elements is called a 2-D array

these are often used to represent matrix or 2nd order tensors

* NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [16]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D Arrays

an array that has 2-D arrays (matrices) as its elements is called 3-D array

these are often used to represent a 3rd order tensor

In [19]:
# create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3
# and 4,5,6:

import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print((arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [20]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### data types in numpy

numpy has some extra data types, and refer to data types with one character, like i for integers, u for unsinged integers etc.

In [23]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6
